# helix apply -f medical.yaml --rsync ./medical
# or,
# helix test -f medical.yaml --rsync ./medical

apiVersion: app.aispec.org/v1alpha1
kind: AIApp
metadata:
  name: Vision Demo - Handwritten Medical Notes
spec:
  assistants:
    - model: Qwen/Qwen2.5-VL-7B-Instruct
      provider: openai
      knowledge:
        - name: pdfs
          rag_settings:
            enable_vision: true
          source:
            filestore:
              path: pdfs
      tests:
        - name: covid
          steps:
            - prompt: "what is the recommended covid practice in the sir ganga ram hospital?"
              expected_output: "The answer should include but not be limited to social distancing and hydroxychloroquine"
