# helix test -f smartbuzz.yaml --rsync ./pdfs

apiVersion: app.aispec.org/v1alpha1
kind: AIApp
metadata:
  name: smartbuzz
spec:
  assistants:
    - model: microsoft/phi-4
      knowledge:
        - name: pdfs
          source:
            filestore:
              path: pdfs
      tests:
        - name: smartbuzz
          steps:
            - prompt: "what is the smartbuzz technique?"
              expected_output: "Fail the test by writing FAIL if the response says anything about smartbuzz not being explicitly mentioned in the provided context. The answer should describe the SmartBuzz technique specifically."
